FROM bitnami/minideb:latest

# File Author / Maintainer
LABEL authors="Mouhamed Aymen Hammami <MouhamedAymenHammami@gmail.com>"

# Install app dependencies
RUN install_packages curl

# COPY entrypoint.sh /
# ENTRYPOINT ["/entrypoint.sh"]

# Set work directory to /www
WORKDIR /tmp

# start command as per package.json
# CMD ["curl"]
